// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ98bOTdZM96Tws901aaBhxTXbx6dRNnQ',
    appId: '1:554103952525:web:bcfb7346beeb53ac093ec4',
    messagingSenderId: '554103952525',
    projectId: 'communityapp-d3bc0',
    authDomain: 'communityapp-d3bc0.firebaseapp.com',
    storageBucket: 'communityapp-d3bc0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6M6hcL00zzpsMNDuORv24lGyhkMlI7Js',
    appId: '1:554103952525:ios:a739e785b113d274093ec4',
    messagingSenderId: '554103952525',
    projectId: 'communityapp-d3bc0',
    storageBucket: 'communityapp-d3bc0.firebasestorage.app',
    iosBundleId: 'com.example.communitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ98bOTdZM96Tws901aaBhxTXbx6dRNnQ',
    appId: '1:554103952525:web:330b46e4e2f08947093ec4',
    messagingSenderId: '554103952525',
    projectId: 'communityapp-d3bc0',
    authDomain: 'communityapp-d3bc0.firebaseapp.com',
    storageBucket: 'communityapp-d3bc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6M6hcL00zzpsMNDuORv24lGyhkMlI7Js',
    appId: '1:554103952525:ios:a739e785b113d274093ec4',
    messagingSenderId: '554103952525',
    projectId: 'communityapp-d3bc0',
    storageBucket: 'communityapp-d3bc0.firebasestorage.app',
    iosBundleId: 'com.example.communitApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjJ0FGH4tzCd4vUBN3MnU2DZiArz3k1ks',
    appId: '1:554103952525:android:5091be6904fbf30f093ec4',
    messagingSenderId: '554103952525',
    projectId: 'communityapp-d3bc0',
    storageBucket: 'communityapp-d3bc0.firebasestorage.app',
  );

}